package gui;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;

public class Accesso {
    private JPanel panel;
    private JPanel panelAccedi;
    private JPanel panelUtente;
    private JButton buttonAccedi;
    private JButton buttonUtente;

    private static JFrame frame;

    public Accesso() {
        buttonAccedi.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Login login = new Login(frame);
                login.frame.setVisible(true);
                frame.dispose();
            }
        });
        buttonUtente.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Home home = new Home(frame);
                home.frame.setVisible(true);
                frame.dispose();
            }
        });
    }

    public static void main(String[] args) {
        frame = new JFrame("Accesso");
        frame.setContentPane(new Accesso().panel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        frame.setSize(500, 200);
        frame.setLocationRelativeTo(null);
        frame.setResizable(false);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelAccedi = new JPanel();
        panelAccedi.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelAccedi.setAlignmentX(0.5f);
        panel.add(panelAccedi);
        panelAccedi.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(55, 0, 0, 0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, this.$$$getFont$$$(null, -1, -1, panelAccedi.getFont()), new Color(-2104859)));
        buttonAccedi = new JButton();
        buttonAccedi.setText("Accedi come amministratore");
        panelAccedi.add(buttonAccedi);
        panelUtente = new JPanel();
        panelUtente.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel.add(panelUtente);
        panelUtente.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(55, 0, 0, 0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        buttonUtente = new JButton();
        buttonUtente.setText("Continua senza accedere");
        panelUtente.add(buttonUtente);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
