package gui;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

public class EliminaCalciatore {
    private JPanel panel;
    private JTable tableGiocatori;
    private JPanel panelGiocatori;
    private JButton button1;

    public static JFrame frame;

    public EliminaCalciatore(JFrame frameChiamante) {
        frame = new JFrame("Elimina calciatore");
        frame.setContentPane(panel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);

        tableGiocatori.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        DefaultTableModel tableModel = new DefaultTableModel(new Object[][]{}, new String[]{"Nome", "Cognome", "Piede", "Sesso", "dataNascita", "dataRitiro", "Squadra"});
        tableGiocatori.setModel(tableModel);
        tableModel.addRow(new Object[]{"Nome", "Cognome", "Piede", "Sesso", "dataNascita", "dataRitiro", "Squadra"});
        tableModel.addRow(new Object[]{"Olivier", "Giroud", "Destro", "M", "30/09/1986", "N/D", "Chelsea"});
        tableModel.addRow(new Object[]{"Cristiano", "Ronaldo", "Destro", "M", "05/02/1985", "N/D", "Juventus"});
        tableModel.addRow(new Object[]{"Lionel", "Messi", "Sinistro", "M", "24/06/1987", "N/D", "Barcellona"});
        tableModel.addRow(new Object[]{"Zlatan", "Ibrahimovic", "Destro", "M", "03/10/1981", "N/D", "Milan"});
        tableModel.addRow(new Object[]{"Gianluigi", "Buffon", "Destro", "M", "28/01/1978", "N/D", "Juventus"});
        tableModel.addRow(new Object[]{"Gianluigi", "Donnarumma", "Destro", "M", "25/02/1999", "N/D", "Milan"});
        tableModel.addRow(new Object[]{"Victor", "Osimhen", "Destro", "M", "29/12/1998", "N/D", "Napoli"});
        tableModel.addRow(new Object[]{"Lorenzo", "Insigne", "Destro", "M", "04/06/1991", "N/D", "Napoli"});
        tableModel.addRow(new Object[]{"Ciro", "Immobile", "Destro", "M", "20/02/1990", "N/D", "Lazio"});
        tableModel.addRow(new Object[]{"Romelu", "Lukaku", "Destro", "M", "13/05/1993", "N/D", "Inter"});
        tableModel.addRow(new Object[]{"Lautaro", "Martinez", "Destro", "M", "22/08/1997", "N/D", "Inter"});
        tableModel.addRow(new Object[]{"Edin", "Dzeko", "Destro", "M", "17/03/1986", "N/D", "Roma"});


    }

    public static void main(String[] args) {
        EliminaCalciatore eliminaCalciatore = new EliminaCalciatore(frame);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelGiocatori = new JPanel();
        panelGiocatori.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel.add(panelGiocatori, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        tableGiocatori = new JTable();
        panelGiocatori.add(tableGiocatori, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        button1 = new JButton();
        button1.setText("Button");
        panelGiocatori.add(button1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
